# Generated by Django 6.0.5 on 2026-05-17 07:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='uploads/%Y/%m/%d/')),
                ('original_filename', models.CharField(max_length=255)),
                ('file_type', models.CharField(max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('extracted', 'Extracted'), ('reviewed', 'Reviewed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ExtractedRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('shift', models.CharField(blank=True, choices=[('A', 'Shift A'), ('B', 'Shift B'), ('C', 'Shift C'), ('', 'Unknown')], max_length=5)),
                ('employee_number', models.CharField(blank=True, max_length=50)),
                ('operation_code', models.CharField(blank=True, max_length=50)),
                ('machine_number', models.CharField(blank=True, max_length=50)),
                ('work_order_number', models.CharField(blank=True, max_length=100)),
                ('quantity_produced', models.IntegerField(blank=True, null=True)),
                ('time_taken', models.FloatField(blank=True, help_text='In hours', null=True)),
                ('raw_extraction', models.JSONField(blank=True, default=dict)),
                ('overall_confidence', models.FloatField(default=0.0)),
                ('has_validation_errors', models.BooleanField(default=False)),
                ('validation_errors', models.JSONField(blank=True, default=list)),
                ('is_reviewed', models.BooleanField(default=False)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewer_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='record', to='documents.document')),
            ],
        ),
        migrations.CreateModel(
            name='FieldConfidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=100)),
                ('confidence', models.FloatField()),
                ('raw_value', models.CharField(blank=True, max_length=500)),
                ('is_uncertain', models.BooleanField(default=False)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_confidences', to='documents.extractedrecord')),
            ],
        ),
    ]
