# Generated by Django 6.0.5 on 2026-05-17 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='extractedrecord',
            name='row_number',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='extractedrecord',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='documents.document'),
        ),
    ]
